extends Node

enum OBJETO {TEXTO, VALOR}

enum TELAS {
	TELA_INICIAL,TELA_PAUSE,TELA_LOADING,
	TELA_CONFIG,TELA_CREDITOS,TELA_BATALHA,
	DESK,
	TUTORIAL
}

const UID_SCENES = {
	TELAS.TELA_INICIAL: "uid://dfup2bdf5sdnw",
	TELAS.TELA_PAUSE: "uid://bwstta8psu4ph",
	TELAS.TELA_LOADING: "uid://ck8l2lqfa2r4y",
	TELAS.TELA_CONFIG: "uid://ds226ph62jpir",
	TELAS.TELA_CREDITOS: "uid://bok2i3ulpkeq8",
	TELAS.TELA_BATALHA: "uid://clk1ysjnbyd46",
	TELAS.DESK: "uid://54vcmnecmgu8",
	TELAS.TUTORIAL: "uid://i3jev2a6unrr",
}

enum ACOES {PARA_CIMA,PARA_BAIXO,PARA_ESQUERDA,PARA_DIREITA,INTERAGIR}
const ACOES_CUSTOM = {
	ACOES.PARA_CIMA: {OBJETO.VALOR: "para_cima", OBJETO.TEXTO: "Mover para cima"},
	ACOES.PARA_BAIXO: {OBJETO.VALOR: "para_baixo", OBJETO.TEXTO: "Mover para baixo"},
	ACOES.PARA_ESQUERDA: {OBJETO.VALOR: "para_esquerda", OBJETO.TEXTO: "Mover para esquerda"},
	ACOES.PARA_DIREITA: {OBJETO.VALOR: "para_direita", OBJETO.TEXTO: "Mover para direita"},
	ACOES.INTERAGIR: {OBJETO.VALOR: "interagir", OBJETO.TEXTO: "Interagir"},
}

enum RESOLUCOES {RES_640X320,RES_1280X720,RES_1920X1080,RES_2560X1440}
const RESOLUCAO_DICT = {
	RESOLUCOES.RES_640X320: {OBJETO.VALOR: Vector2i(640, 320), OBJETO.TEXTO: "640x320"},
	RESOLUCOES.RES_1280X720: {OBJETO.VALOR: Vector2i(1280, 720), OBJETO.TEXTO: "1280x720"},
	RESOLUCOES.RES_1920X1080: {OBJETO.VALOR: Vector2i(1920, 1080), OBJETO.TEXTO: "1920x1080"},
	RESOLUCOES.RES_2560X1440: {OBJETO.VALOR: Vector2i(2560, 1440), OBJETO.TEXTO: "2560x1440"},
}

enum MODOS {JANELA,TELA_CHEIA}
const MODO_DICT = {
	MODOS.JANELA: {OBJETO.VALOR: Window.MODE_WINDOWED, OBJETO.TEXTO: "Janela"},
	MODOS.TELA_CHEIA: {OBJETO.VALOR: Window.MODE_EXCLUSIVE_FULLSCREEN, OBJETO.TEXTO: "Tela cheia"},
}
