extends Node

enum OBJETO {TEXTO, VALOR}

enum CENAS_ORDENADAS {
	SALA_RH, FABRICA_DE_BRINQUEDO, CORREDOR_2, CORREDOR_1,
	SUPERVISOR, ESCRITORIO, PONTO_DE_ONIBUS, CASA
}

const UID_CENAS = {
	CENAS_ORDENADAS.SALA_RH: "uid://bu8mvji7biuvu",
	CENAS_ORDENADAS.FABRICA_DE_BRINQUEDO: "uid://c6cjuu7pys546",
	CENAS_ORDENADAS.CORREDOR_2: "uid://bp232bjl5tduo",
	CENAS_ORDENADAS.CORREDOR_1: "uid://d3ivfwg2ejlkc",
	CENAS_ORDENADAS.SUPERVISOR: "uid://deripe8neoc8s",
	CENAS_ORDENADAS.ESCRITORIO: "uid://d2ne07f0i25nk",
	CENAS_ORDENADAS.PONTO_DE_ONIBUS: "uid://dbbswc4ne2pvo",
	CENAS_ORDENADAS.CASA: "uid://dbbswc4ne2pvo",
}

enum TELAS {
	TELA_INICIAL,TELA_PAUSE,TELA_LOADING,
	TELA_CONFIG,TELA_CREDITOS,TELA_BATALHA,
	DESK, TUTORIAL, CENARIO
}

const UID_SCENES = {
	TELAS.TELA_INICIAL: "uid://dfup2bdf5sdnw",
	TELAS.TELA_PAUSE: "uid://bwstta8psu4ph",
	TELAS.TELA_LOADING: "uid://ck8l2lqfa2r4y",
	TELAS.TELA_CONFIG: "uid://ds226ph62jpir",
	TELAS.TELA_CREDITOS: "uid://bok2i3ulpkeq8",
	TELAS.TELA_BATALHA: "uid://clk1ysjnbyd46",
	TELAS.DESK: "uid://54vcmnecmgu8",
	TELAS.TUTORIAL: "uid://i3jev2a6unrr",
	TELAS.CENARIO: "uid://b3o4ai3dyu5jn"
}


enum ACOES {PARA_CIMA,PARA_BAIXO,PARA_ESQUERDA,PARA_DIREITA,INTERAGIR}
const ACOES_CUSTOM = {
	ACOES.PARA_CIMA: {OBJETO.VALOR: "para_cima", OBJETO.TEXTO: "Mover para cima"},
	ACOES.PARA_BAIXO: {OBJETO.VALOR: "para_baixo", OBJETO.TEXTO: "Mover para baixo"},
	ACOES.PARA_ESQUERDA: {OBJETO.VALOR: "para_esquerda", OBJETO.TEXTO: "Mover para esquerda"},
	ACOES.PARA_DIREITA: {OBJETO.VALOR: "para_direita", OBJETO.TEXTO: "Mover para direita"},
	ACOES.INTERAGIR: {OBJETO.VALOR: "interagir", OBJETO.TEXTO: "Interagir"},
}

enum RESOLUCOES {RES_640X320,RES_1280X720,RES_1920X1080,RES_2560X1440}
const RESOLUCAO_DICT = {
	RESOLUCOES.RES_640X320: {OBJETO.VALOR: Vector2i(640, 320), OBJETO.TEXTO: "640x320"},
	RESOLUCOES.RES_1280X720: {OBJETO.VALOR: Vector2i(1280, 720), OBJETO.TEXTO: "1280x720"},
	RESOLUCOES.RES_1920X1080: {OBJETO.VALOR: Vector2i(1920, 1080), OBJETO.TEXTO: "1920x1080"},
	RESOLUCOES.RES_2560X1440: {OBJETO.VALOR: Vector2i(2560, 1440), OBJETO.TEXTO: "2560x1440"},
}

enum MODOS {JANELA,TELA_CHEIA}
const MODO_DICT = {
	MODOS.JANELA: {OBJETO.VALOR: Window.MODE_WINDOWED, OBJETO.TEXTO: "Janela"},
	MODOS.TELA_CHEIA: {OBJETO.VALOR: Window.MODE_EXCLUSIVE_FULLSCREEN, OBJETO.TEXTO: "Tela cheia"},
}
